# Generated by Django 5.0.6 on 2024-06-01 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_rename_review_book_review_review_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_book",
                to="store.items",
            ),
        ),
    ]
