# Generated by Django 5.0.6 on 2024-05-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Напишите название книги и т.д.')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Загрузите фото')),
                ('description', models.TextField(verbose_name='НАпишите описание книги')),
                ('music', models.FileField(blank=True, upload_to='audio/', verbose_name='Загрузите песню')),
                ('video', models.URLField(verbose_name='Загрузите ввидео ссылку')),
                ('genre', models.CharField(choices=[('Хоррор', 'Хоррор'), ('Фантастика', 'Фантастика'), ('Романтика', 'Романтика')], max_length=100, verbose_name='Выберите жанр книги')),
                ('time_books', models.PositiveIntegerField(verbose_name='Укажите время книги')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=100, verbose_name='Укажите автора книги')),
                ('rate', models.PositiveIntegerField(verbose_name='Укажите среднюю оценку этой книги')),
            ],
        ),
    ]
