# Generated by Django 5.0.6 on 2024-05-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Список книг'},
        ),
    ]
